### ISSUE TITLE
Keyboard incompatibility

### ISSUE THREAD

**Issue by MiguelAngelCoronado** [SonicFreak94/sadx-idle-chatter#1]
Aside from Xinput, I can't locate the Z button in the keyboard. Since The Z key is attack by default it must be something else I'm missing

**Comment by SonicFreak94** [comment]
In vanilla SADX, the keyboard only has bindings for A B X & Y. I've started development of keyboard and mouse support in [sadx-input-mod](https://github.com/SonicFreak94/sadx-input-mod) which should allow for control customization, and that will certainly allow extended button support (C, D, Z). I recommend following that repo for updates.
